"""
============================================
Branding Model
LinkedIn Branding Assistant
============================================
Handles branding reports, generated content, and history storage.
"""

from datetime import datetime, timezone
from bson import ObjectId
from database import Database


class BrandingModel:
    """Model for branding reports and analytics."""

    REPORTS_COLLECTION = 'branding_reports'
    POSTS_COLLECTION = 'generated_posts'
    HEADLINES_COLLECTION = 'generated_headlines'
    ABOUT_COLLECTION = 'generated_abouts'

    # ── Branding Reports ──────────────────────────────

    @classmethod
    def save_report(cls, user_id, profile_data, score, recommendations, breakdown):
        """Save a branding analysis report."""
        collection = Database.get_collection(cls.REPORTS_COLLECTION)
        report = {
            'user_id': ObjectId(user_id),
            'profile_data': profile_data,
            'score': score,
            'recommendations': recommendations,
            'breakdown': breakdown,
            'created_at': datetime.now(timezone.utc)
        }
        result = collection.insert_one(report)
        report['_id'] = result.inserted_id
        return report

    @classmethod
    def get_latest_report(cls, user_id):
        """Get the most recent branding report for a user."""
        collection = Database.get_collection(cls.REPORTS_COLLECTION)
        return collection.find_one(
            {'user_id': ObjectId(user_id)},
            sort=[('created_at', -1)]
        )

    @classmethod
    def get_all_reports(cls, user_id, limit=10):
        """Get all branding reports for a user."""
        collection = Database.get_collection(cls.REPORTS_COLLECTION)
        return list(collection.find(
            {'user_id': ObjectId(user_id)}
        ).sort('created_at', -1).limit(limit))

    # ── Generated Posts ───────────────────────────────

    @classmethod
    def save_post(cls, user_id, content, category, post_length='medium'):
        """Save a generated LinkedIn post."""
        collection = Database.get_collection(cls.POSTS_COLLECTION)
        post = {
            'user_id': ObjectId(user_id),
            'content': content,
            'category': category,
            'post_length': post_length,
            'created_at': datetime.now(timezone.utc)
        }
        result = collection.insert_one(post)
        post['_id'] = result.inserted_id
        return post

    @classmethod
    def get_user_posts(cls, user_id, limit=20):
        """Get all generated posts for a user."""
        collection = Database.get_collection(cls.POSTS_COLLECTION)
        return list(collection.find(
            {'user_id': ObjectId(user_id)}
        ).sort('created_at', -1).limit(limit))

    @classmethod
    def get_posts_count(cls, user_id):
        """Get total number of posts generated by a user."""
        collection = Database.get_collection(cls.POSTS_COLLECTION)
        return collection.count_documents({'user_id': ObjectId(user_id)})

    # ── Generated Headlines ──────────────────────────

    @classmethod
    def save_headline(cls, user_id, headlines, skills, experience, career_goal):
        """Save generated headlines."""
        collection = Database.get_collection(cls.HEADLINES_COLLECTION)
        doc = {
            'user_id': ObjectId(user_id),
            'headlines': headlines,
            'input_data': {
                'skills': skills,
                'experience': experience,
                'career_goal': career_goal
            },
            'created_at': datetime.now(timezone.utc)
        }
        result = collection.insert_one(doc)
        doc['_id'] = result.inserted_id
        return doc

    @classmethod
    def get_user_headlines(cls, user_id, limit=10):
        """Get all generated headlines for a user."""
        collection = Database.get_collection(cls.HEADLINES_COLLECTION)
        return list(collection.find(
            {'user_id': ObjectId(user_id)}
        ).sort('created_at', -1).limit(limit))

    # ── Generated About Sections ─────────────────────

    @classmethod
    def save_about(cls, user_id, about_content, input_data):
        """Save a generated about section."""
        collection = Database.get_collection(cls.ABOUT_COLLECTION)
        doc = {
            'user_id': ObjectId(user_id),
            'about_content': about_content,
            'input_data': input_data,
            'created_at': datetime.now(timezone.utc)
        }
        result = collection.insert_one(doc)
        doc['_id'] = result.inserted_id
        return doc

    @classmethod
    def get_user_abouts(cls, user_id, limit=10):
        """Get all generated about sections for a user."""
        collection = Database.get_collection(cls.ABOUT_COLLECTION)
        return list(collection.find(
            {'user_id': ObjectId(user_id)}
        ).sort('created_at', -1).limit(limit))

    # ── Aggregate History ─────────────────────────────

    @classmethod
    def get_full_history(cls, user_id, limit=50):
        """Get complete generation history for a user across all types."""
        history = []

        # Gather posts
        posts = cls.get_user_posts(user_id, limit)
        for p in posts:
            history.append({
                'type': 'post',
                'content': p.get('content', ''),
                'category': p.get('category', ''),
                'created_at': p.get('created_at'),
                'id': str(p['_id'])
            })

        # Gather headlines
        headlines = cls.get_user_headlines(user_id, limit)
        for h in headlines:
            history.append({
                'type': 'headline',
                'content': h.get('headlines', []),
                'input_data': h.get('input_data', {}),
                'created_at': h.get('created_at'),
                'id': str(h['_id'])
            })

        # Gather about sections
        abouts = cls.get_user_abouts(user_id, limit)
        for a in abouts:
            history.append({
                'type': 'about',
                'content': a.get('about_content', ''),
                'input_data': a.get('input_data', {}),
                'created_at': a.get('created_at'),
                'id': str(a['_id'])
            })

        # Gather branding reports
        reports = cls.get_all_reports(user_id, limit)
        for r in reports:
            history.append({
                'type': 'branding_report',
                'score': r.get('score', 0),
                'recommendations': r.get('recommendations', []),
                'created_at': r.get('created_at'),
                'id': str(r['_id'])
            })

        # Sort by created_at descending
        history.sort(key=lambda x: x.get('created_at', datetime.min.replace(tzinfo=timezone.utc)), reverse=True)

        return history[:limit]

    @classmethod
    def delete_history_item(cls, user_id, item_id, item_type):
        """Delete a specific history item."""
        collection_map = {
            'post': cls.POSTS_COLLECTION,
            'headline': cls.HEADLINES_COLLECTION,
            'about': cls.ABOUT_COLLECTION,
            'branding_report': cls.REPORTS_COLLECTION
        }

        collection_name = collection_map.get(item_type)
        if not collection_name:
            return False

        collection = Database.get_collection(collection_name)
        result = collection.delete_one({
            '_id': ObjectId(item_id),
            'user_id': ObjectId(user_id)
        })
        return result.deleted_count > 0
